# Generated by Django 5.2.1 on 2025-07-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='reading_1',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='reading_3',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='reading_4',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='reading_5',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='entry_source',
            field=models.CharField(choices=[('customer_staff_entry', 'Customer Entry')], default='customer_staff_entry', max_length=30),
        ),
        migrations.CreateModel(
            name='ReadingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_no', models.CharField(max_length=100)),
                ('reading_1', models.PositiveIntegerField(default=0)),
                ('reading_2', models.PositiveIntegerField(default=0)),
                ('reading_3', models.PositiveIntegerField(default=0)),
                ('reading_4', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('entry_source', models.CharField(choices=[('staff_entry', 'Staff Entry')], default='staff_entry', max_length=30)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videostore.machine')),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingDataPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reading_photos/')),
                ('reading_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='videostore.readingdata')),
            ],
        ),
        migrations.DeleteModel(
            name='GameDataPhoto',
        ),
    ]
