# Generated by Django 5.2.1 on 2025-07-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='machine_number',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='expense_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='expense_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('tea', 'Tea'), ('water', 'Water'), ('lightbill', 'Light Bill'), ('police', 'Police'), ('goodluck', 'Good Luck'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videostore.store')),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videostore.machine'),
        ),
    ]
