# Generated by Django 5.2.4 on 2026-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0002_remove_gamedata_photo_remove_gamedata_reading_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
