# Generated by Django 5.2.1 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='entry_source',
            field=models.CharField(choices=[('customer_staff_entry', 'Customer Entry'), ('staff_entry', 'Staff Entry')], default='customer_staff_entry', max_length=30),
        ),
    ]
